version: "3"
services:
  landing_page:
    image: nodejsClient-local-image
    
    ports:
      - "3000:3000"
  prediction_disease :
    image: python-local-image
    ports:
      - "3030:3030"
  medical_record :
    image: nodejs1-local-image
    ports:
      - "3000:3000"